### ISSUE TITLE
don't forget function prologue is muy importante :)

### ISSUE THREAD

**Issue by panaC** [msukhare/LibftASM#1]
https://github.com/msukhare/LibftASM/blob/e0a06ed220b132d194eba01ef100e125928f8344/srcs/ft_strlen.s#L5-L6

https://en.wikipedia.org/wiki/Function_prologue

**Comment by panaC** [comment]
you did it , my bad  🤣

**Comment by msukhare** [comment]
Go back to work pls

**Comment by msukhare** [comment]
And next time read the code pls
